version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    restart: always
    user: root  # Chạy container với quyền root
    networks:
      - webnet

networks:
  webnet:
    driver: bridge