version: '3.8'
services:
  web:
    build: .
    ports:
      - "10000:10000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    restart: always